## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
notifications:
  email: false
git:
  depth: 99999999

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ExecutableSpecifications")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
